apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
spec:
  selector:
    app: springboot-k8s-demo
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort

